# Generated by Django 5.2 on 2025-05-23 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta1', models.PositiveSmallIntegerField()),
                ('pregunta2', models.PositiveSmallIntegerField()),
                ('pregunta3', models.PositiveSmallIntegerField()),
                ('pregunta4', models.PositiveSmallIntegerField()),
                ('pregunta5', models.PositiveSmallIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
