# Generated by Django 5.2 on 2025-05-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_contadorvisitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='residuo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_residuos/'),
        ),
    ]
